In [1]:
import pandas as pd

# Series

A series is a one dimensional array of data

In [2]:
print('\nSeries:\n')

pop_list = [724305, 65558, 64674, 89438]

# index is used to give the series a specified index set
series_pop = pd.Series(pop_list, index=['seattle', 'redmond', 'sammamish', 'kirkland'])

print(series_pop)

# Print out series data by index name
print('\nPopulation in Seattle:', series_pop['seattle'])

Series:

seattle      724305
redmond       65558
sammamish     64674
kirkland      89438
dtype: int64

Population in Seattle: 724305

<hr>

# Dataframe

A dataframe is a two dimensional array of data

In [3]:
print('\nDataframe:\n')

populations = {
  'city': ['seattle', 'redmond', 'sammamish', 'kirkland'],
  'population': [724305, 65558, 64674, 89438]
}

df_pop = pd.DataFrame(populations)

df_pop

Dataframe:

        city  population
0    seattle      724305
1    redmond       65558
2  sammamish       64674
3   kirkland       89438

### Find data at a specific index of the dataframe

In [4]:
print('\nData at index 2:\n')
print(df_pop.loc[[2]])

Data at index 2:

        city  population
2  sammamish       64674

### Find data at multiple indexes of the dataframe

In [5]:
print('\nData at index 1 and 3:\n')
print(df_pop.loc[[1, 3]])

Data at index 1 and 3:

       city  population
1   redmond       65558
3  kirkland       89438

### Give specific index labels to the rows instead of the standard 0,1,2...

In [6]:
annual_pop = {
  'men': [357372, 354461, 354015, 353846],
  'women': [351451, 349454, 349103, 348463]
}

df_annual_pop = pd.DataFrame(annual_pop, index=[2019, 2018, 2017, 2016])

df_annual_pop

         men   women
2019  357372  351451
2018  354461  349454
2017  354015  349103
2016  353846  348463